### PR TITLE
[FEAT] Add images

### PR DESCRIPTION
**Pull request by vKeeReaL**

### CODE REVIEW

**Review by GeorgePlotnikov — APPROVED** [review]
Looks nice. Did you draw it?

**Comment by GeorgePlotnikov** [comment]
Please put it under assets/images directory

**Comment by vKeeReaL** [comment]
> Looks nice. Did you draw it?

Sure

**Comment by vKeeReaL** [comment]
> Please put it under assets/images directory

mb src/assets/images ?

**Comment by GeorgePlotnikov** [comment]
I think we can use them not only in the codebase but in the documentation as well, right?

**Comment by vKeeReaL** [comment]
> I think we can use them not only in the codebase but in the documentation as well, right?

Sure

**Pull request merged**
